# Use the latest 2.1 version of CircleCI pipeline process engine.

version: 2.1

# Define a job to be invoked later in a workflow.

jobs:
  print-hello: 
    docker:
      - image: cirlceci/node:13.8.0
    steps:
      #- checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  print-world:
    docker:
      - image: cirlceci/node:13.8.0
    steps:
      #- checkout
      - run:
          name: "Say world"
          command: "echo  World!"
       

# Invoke jobs via workflows
workflows:
  say-hello-workflow:
    jobs:
      - print-hello
      - print-world:
          requires:
            -print-hello 
